"""
CareFlow - Member 3 - DFG validation

Validates the DFG edge CSV generated by generate_dfg.py.
"""

from pathlib import Path
import pandas as pd


BASE_DIR = Path(__file__).resolve().parent
DFG_FILE = BASE_DIR / "outputs" / "dfg_edges.csv"


def main():
    if not DFG_FILE.exists():
        raise FileNotFoundError(
            "dfg_edges.csv was not found. Run generate_dfg.py first."
        )

    df = pd.read_csv(DFG_FILE)

    required = [
        "Source_Activity",
        "Target_Activity",
        "Frequency",
    ]

    missing = [col for col in required if col not in df.columns]

    if missing:
        raise ValueError(f"Missing DFG column(s): {missing}")

    if df.empty:
        raise ValueError("DFG contains no transitions.")

    if df["Frequency"].isna().any():
        raise ValueError("DFG contains missing frequency values.")

    if (df["Frequency"] <= 0).any():
        raise ValueError("DFG contains zero or negative frequencies.")

    if df[["Source_Activity", "Target_Activity"]].isna().any().any():
        raise ValueError("DFG contains missing activity names.")

    print("DFG validation PASSED")
    print(f"Transitions : {len(df)}")
    print(f"Total paths : {int(df['Frequency'].sum())}")
    print("\nTop 10 directly-follows relationships:")
    print(df.head(10).to_string(index=False))


if __name__ == "__main__":
    main()
